spring.application.name=coworkingbooking
spring.datasource.url=${POSTGRES_URL}
spring.datasource.username=${POSTGRES_USER}
spring.datasource.password=${POSTGRES_PASSWORD}
#spring.datasource.url=jdbc:postgresql://localhost:5433/backend_db
#spring.datasource.username=backend_usr
#spring.datasource.password=backend_pwd
spring.datasource.driver-class-name=org.postgresql.Driver
springdoc.api-docs.path=/api-docs